v1.1.yml, v1.2.yml
- native_language isn't generally supported
- operation name wrong
=> Fix minor issues

v1.1.yml, v1.2.yml
Adds the events endpoints and definitions.
The names of the events objects are a bit weird because they have to match the discriminator (i.e. the way we determine polymorphic type) which is the type field.
=> Events endpoints and definitions

v1.1.yml, v1.2.yml
=> Fix events yml definition

v1.2-client.yml
Slightly different from the definitions we have for the documentation.
The client libraries have removed some of the features we don't think
are as useful and would just add clutter.
=> Add client swagger definition

v1.1.yml, v1.2.yml
=> Remove count param

Makefile, README.md, full.yml, main.go, v1.1-events.yml, v1.1.yml, v1.2-client.yml, v1.2-events.yml, v1.2.yml
This change adds a few things to the schema:
- Enum information
- Extra information so we can get closer to replicating www.clever.com/schema from this schema. There's still some work that needs to be done - I believe just adding examples and descriptions
- The google_apps field
- Clean up a few of the x-nullable definitions and a few other things
=> Clean up schema

full-v2.yml, v2.0-client.yml, v2.0-events.yml, v2.0.yml
We also normalize phone type on contacts:
https://github.com/Clever/pipeline-data-quality/blob/master/valuemapper/phonetypes.yml
=> Enumerate Contact phone type

V2/generate.go, full-v2.yml, v2.1-client.yml, v2.1-events.yml, v2.1.yml
Add these fields to v2.1:
- district:
- portal_url
- login_methods
- district_contact
- goals_enabled
- students:
- gender enum X
Generate files for both v2.0 and v2.1. Strip out all v2.1 fields for v2.0 file.
Note: v2.0 files did not change, which is expected 👍
=> SYNC-1097 v2.1

V2/generate.go, full-v2.yml, v2.0.yml, v2.1-client.yml, v2.1.yml
=> SYNC-1097 v2.1 counts

V2/generate.go, full-v2.yml, v2.1-client.yml, v2.1-events.yml, v2.1.yml
extension field filtering in this PR: https://github.com/Clever/swagger-api/pull/28
=> SYNC-1097 enrollments ext

full-v2.yml, v2.1-client.yml, v2.1-events.yml, v2.1.yml
**JIRA:**
https://clever.atlassian.net/browse/SYNC-1097
Allow blank option for enums in our spec, so apps know it's a valid value.
=> Add blank option for enums

V2/generate.go
An addition to https://github.com/Clever/swagger-api/pull/32
=> Modify generate file for remove v2.1 changes from v2.0

full-v2.yml, v2.1-client.yml, v2.1.yml
https://github.com/Clever/sis-api/blob/e6caa3dc7f691910734233faff19880db52fce87/routes/sis/endpoints.ts#L53
=> enum "true" for count param

full-v2.yml, v2.1-client.yml, v2.1.yml
need to have default value in the drop down https://github.com/Clever/swagger-api/pull/34
=> SYNC-1097 count more enum

main.go, v1/generate.go, v2.1-client.yml, v2.1-events.yml, v2.1.yml, v2/generate.go
https://clever.atlassian.net/browse/SYNC-1320
Adds new fields `department` and extension fields for SchoolAdmins in API v2.1.
=> Add department and extension fields to v2.1

v2.0-client.yml, v2.0-events.yml, v2.0.yml, v2.1-client.yml, v2.1-events.yml, v2.1.yml
[SOC-2954](https://clever.atlassian.net/browse/SOC-2954?atlOrigin=eyJpIjoiN2I0YzM2YTM0MTJiNDQ2MThlYWUzMGFkZWY3OThjZDgiLCJwIjoiaiJ9)
Per request from PE, removing middle name from schema. Also including department and ext in the full v2 schema file.
=> Remove middle name from schema

v2.0-client.yml, v2.0-events.yml, v2.0.yml, v2.1-client.yml, v2.1-events.yml, v2.1.yml
Previous PR removed middle name from all user collections, changing in this PR to only remove middle name for district and school admins
=> remove middle name only for admins

full-v2.yml, v2.0-events.yml, v2.0.yml, v2.1-client.yml, v2.1-events.yml, v2.1.yml, v2/generate.go
We've been making these changes in the individual files instead of the "full" file and generating them.
This adds the changes to the v2 full file and fixes generation.
=> Fix v2 full file

full-v3.yml, v3.0-client.yml, v3.0-events.yml, v3.0.yml
[SYNC-2075](https://clever.atlassian.net/browse/SYNC-2075)
A few more changes needed for Swagger to be happy. Verified with a tool that it's not horribly misconfigured.
=> SYNC-2075 try again

full-v3.yml, v3.0-client.yml, v3.0.yml
=> Add primary parameters

full-v3.yml, v3.0-client.yml, v3.0-events.yml, v3.0.yml
[SYNC-2144](https://clever.atlassian.net/browse/SYNC-2144)
Some endpoints could timeout. Return errors that make sense if that happens.
=> SYNC-2144 Timeouts

full-v3.yml, v3.0-client.yml, v3.0-events.yml, v3.0.yml
That's all.
Thanks Zach for finding https://clever.slack.com/archives/CPQUXRDPY/p1613066465041700
=> SYNC-2153 district_admin in role should be districtadmin

full-v3.yml, v3.0-client.yml, v3.0-events.yml, v3.0.yml
Reverts Clever/swagger-api#55
To be merged with https://github.com/Clever/sis-api/pull/373
=> Revert "SYNC-2153 district_admin in role should be districtadmin"

full-v3.yml, v3.0-client.yml, v3.0.yml
Removing invalid param from section/id/users endpoint
=> remove primary param from section users endpoint

full-v2.yml, full-v3.yml, v2.1-client.yml, v2.1.yml, v3.0-client.yml, v3.0.yml
added "false" and "undefined" to the count parameter under the /student section in v2
added "true", "false", and "undefined" to the count parameter under the /users section in v3
added "true", "false", and "undefined" to count params of all endpoints in v2 and v3
=> Fix count param shapi 286

go.mod, go.sum, golang.mk
https://clever.atlassian.net/browse/INFRANG-5578
This PR updates go to version 1.21. Welcome to the future. 
Extensive testing done in workers, services, wag etc. Nothing specific to this repo though. 
Will be an easy rollback if something breaks. 
#
=> upgrade to go 1.21
